main:
  - name: Resources
    url: /resources/
    weight: 1
  - name: Working Group Members
    url: /authors/twg/
    weight: 2
  - name: Contact & Services
    url: /contact-and-services/
    weight: 3